"""escalate — routes low-confidence or high-stakes cases to a human advisor.

Trigger: escalation == True (set by the guardrail node).
Reads:   escalation_reason.
Writes:  notification to advisor queue, delivery-hold flag.
Calls:   n8n webhook → human advisor queue (Slack, email, CRM ticket).

Escalation criteria (from LLD § 7.2 and the v5 architecture):
  - High sum-assured cases
  - Pre-existing conditions requiring expert judgment
  - NRI status
  - Low confidence score (retrieval agreement + self-consistency below threshold)

This node holds ``output`` for advisor sign-off instead of releasing
it immediately. The output was already generated by explanation_report
(which runs regardless of escalation — AGENTS.md rule 4).
"""
